### ISSUE TITLE
Fix test for using external services

### ISSUE THREAD

**Issue by maZahaca** [redco/redcode-currency-rate#11]
Do NOT use external services in test, need to mock them to add more stability to tests

**Comment by maZahaca** [comment]
One more [provider](https://github.com/redco/redcode-currency-rate/blob/master/tests/CbrCurrencyRateProviderTest.php#L131) is still using external service.

@remedge Could you look on this? And do almost the same as you did before + a bit refactoring of CbrProvider

**Comment by remedge** [comment]
@maZahaca i'll do my best)

**Comment by remedge** [comment]
Here is the PR - https://github.com/redco/redcode-currency-rate/pull/14
