### ISSUE TITLE
Add yahooapis as provider

### ISSUE THREAD

**Issue by maZahaca** [redco/redcode-currency-rate#8]
Query example
http://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20yahoo.finance.xchange%20where%20pair%20in%20%28%22USDRUB%22,%20%22USDJPY%22,%20%22USDBGN%22,%20%22USDCZK%22,%20%22USDDKK%22,%20%22USDGBP%22,%20%22USDHUF%22,%20%22USDLTL%22,%20%22USDLVL%22,%20%22USDPLN%22,%20%22USDRON%22,%20%22USDSEK%22,%20%22USDCHF%22,%20%22USDNOK%22,%20%22USDHRK%22,%20%22USDRUB%22,%20%22USDTRY%22,%20%22USDAUD%22,%20%22USDBRL%22,%20%22USDCAD%22,%20%22USDCNY%22,%20%22USDHKD%22,%20%22USDIDR%22,%20%22USDILS%22,%20%22USDINR%22,%20%22USDKRW%22,%20%22USDMXN%22,%20%22USDMYR%22,%20%22USDNZD%22,%20%22USDPHP%22,%20%22USDSGD%22,%20%22USDTHB%22,%20%22USDZAR%22,%20%22USDISK%22%29&env=store://datatables.org/alltableswithkeys

**Comment by remedge** [comment]
Hi again! I found a great thread about potencial providers - http://stackoverflow.com/questions/3139879/how-do-i-get-currency-exchange-rates-via-an-api-such-as-google-finance

So, i suggest to add [openexchangerates.org](openexchangerates.org) and [currencylayer.com](https://currencylayer.com/) also besides yahooapis. It requires an extended accounts to these services, but it is not a big problem.

What do you mind?

**Comment by remedge** [comment]
Please, take a look into PR - https://github.com/redco/redcode-currency-rate/pull/12

**Comment by maZahaca** [comment]
Thanks for quality code!
